[package]
name = "wasm_fantasia_module"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
spacetimedb = "=1.11.2"
wasm-fantasia-shared = { path = "../shared" }
glam = { workspace = true }

[lints]
workspace = true
